### PR TITLE
Added the GenericContextMenu

### PR DESCRIPTION
**Pull request by EthanHair**
This should probably be a major version change since there are major dependecy changes and it no longer supports dotnet 6

### CODE REVIEW

**Comment by Psypher9** [comment]
Good point, yeah I can release it as a major version. Do you need this package right now or can we wait to release until a few other things change?

**Review by Psypher9 — CHANGES_REQUESTED** [review]
Actually, even if you don't need it right now as a package, I just thought about how we have these dependencies now but they're not setup by default in dependency injection, so we should probably add that as well

**Comment by EthanHair** [comment]
I don't need it right now. Just at some point in the future it can be removed from Shipping Center and use the one from here. I'm not sure how to set the dependencies up in in dependency injection

**Comment by Psypher9** [comment]
What I was thinking was updating the ServiceCollection extensions add `MudBlazorServices` and also 

```csharp
builder.Services.AddScoped<IComponentBus, ComponentBus>();
builder.Services.AddScoped<ComponentBus>(sp => sp.GetRequiredService<IComponentBus>() as ComponentBus);
```
 to here
``` csharp
public static IServiceCollection AddBlazorToolkit(this IServiceCollection services)
    {
        services.TryAddSingleton<IPrintService, PrintService>();
        services.TryAddSingleton<IDownloadService, DownloadService>();
        return services;
    }

```

**Comment by EthanHair** [comment]
Ah I missed the extensions

**Pull request merged**
